from __future__ import annotations
from .models import DeviceRisk

ACTION_RISKS: dict[str, DeviceRisk] = {
    "system.get_state": DeviceRisk.READ,
    "window.list": DeviceRisk.READ,
    "window.foreground": DeviceRisk.READ,
    "process.list": DeviceRisk.READ,
    "clipboard.read": DeviceRisk.READ,
    "audio.list_devices": DeviceRisk.READ,
    "audio.get_defaults": DeviceRisk.READ,
    "camera.list": DeviceRisk.READ,
    "filesystem.inspect": DeviceRisk.READ,
    "filesystem.list": DeviceRisk.READ,
    "filesystem.read": DeviceRisk.READ,
    "filesystem.search": DeviceRisk.READ,
    "settings.list_pages": DeviceRisk.READ,
    "accessibility.inspect": DeviceRisk.READ,
    "accessibility.find": DeviceRisk.READ,
    "browser.pages": DeviceRisk.READ,
    "browser.dom.inspect": DeviceRisk.READ,
    "browser.dom.find": DeviceRisk.READ,
    "vision.capture": DeviceRisk.READ,
    "vision.target": DeviceRisk.READ,

    "monitor.list": DeviceRisk.READ,
"filesystem.exists": DeviceRisk.READ,

"window.focus": DeviceRisk.LOW,
    "window.move": DeviceRisk.LOW,
    "window.minimize": DeviceRisk.LOW,
    "window.maximize": DeviceRisk.LOW,
"window.place": DeviceRisk.LOW,
    "application.launch": DeviceRisk.LOW,
    "notification.send": DeviceRisk.LOW,
    "settings.open": DeviceRisk.LOW,
    "audio.set_evie_device": DeviceRisk.LOW,
    "audio.set_volume": DeviceRisk.LOW,
    "filesystem.create_directory": DeviceRisk.LOW,
    "accessibility.focus": DeviceRisk.LOW,
    "accessibility.select": DeviceRisk.LOW,
    "browser.navigate": DeviceRisk.LOW,
    "vision.pointer_move": DeviceRisk.LOW,

    "window.close": DeviceRisk.MEDIUM,
"clipboard.write": DeviceRisk.MEDIUM,
    "filesystem.write": DeviceRisk.MEDIUM,
    "filesystem.copy": DeviceRisk.MEDIUM,
    "filesystem.move": DeviceRisk.MEDIUM,
    "filesystem.rename": DeviceRisk.MEDIUM,
    "microphone.capture": DeviceRisk.MEDIUM,
    "camera.capture": DeviceRisk.MEDIUM,
    "process.terminate": DeviceRisk.MEDIUM,
    "system.lock_workstation": DeviceRisk.MEDIUM,
    "accessibility.invoke": DeviceRisk.MEDIUM,
    "accessibility.set_value": DeviceRisk.MEDIUM,
    "accessibility.toggle": DeviceRisk.MEDIUM,
    "browser.dom.click": DeviceRisk.MEDIUM,
    "browser.dom.fill": DeviceRisk.MEDIUM,
    "browser.dom.check": DeviceRisk.MEDIUM,
    "browser.dom.select": DeviceRisk.MEDIUM,
    "browser.dom.press": DeviceRisk.MEDIUM,
    "vision.click": DeviceRisk.MEDIUM,

    "filesystem.delete": DeviceRisk.HIGH,
    "settings.change": DeviceRisk.HIGH,
    "process.terminate_critical": DeviceRisk.HIGH,
    "system.shutdown": DeviceRisk.HIGH,
    "system.restart": DeviceRisk.HIGH,
    "system.sleep": DeviceRisk.HIGH,
}

def get_action_risk(action: str) -> DeviceRisk:
    return ACTION_RISKS.get(str(action), DeviceRisk.HIGH)
